table Dates
	lineageTag: b4d7a6be-2852-4a2d-bd3e-46e8bc1ae526

	column Date
		dataType: int64
		formatString: 0
		lineageTag: 0b386c02-4602-4da4-9b6d-e1cf745c4843
		summarizeBy: sum
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

	column 'Day Name'
		dataType: string
		lineageTag: cfdb2f55-0a66-4c63-ba7e-681dead67576
		summarizeBy: none
		sourceColumn: Day Name

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		formatString: 0
		lineageTag: de4e79c7-ff75-45b4-b9a6-4205accaa6b4
		summarizeBy: sum
		sourceColumn: Day

		annotation SummarizationSetBy = Automatic

	column Week
		dataType: int64
		formatString: 0
		lineageTag: 02048664-0e4b-4910-aff8-6c1bded92c3d
		summarizeBy: sum
		sourceColumn: Week

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		formatString: 0
		lineageTag: 034a0bd5-c982-4f5c-bcd7-929412960c33
		summarizeBy: sum
		sourceColumn: Month

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: int64
		formatString: 0
		lineageTag: e9294e57-9c99-4bb9-8a3c-57695bab7eb9
		summarizeBy: sum
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		formatString: 0
		lineageTag: 6f3a6123-fcbc-4bf2-94ea-f71f126231da
		summarizeBy: sum
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column Column8
		dataType: string
		lineageTag: 6c4d6fc9-8224-4675-83f0-45650b1749a0
		summarizeBy: none
		sourceColumn: Column8

		annotation SummarizationSetBy = Automatic

	column Column9
		dataType: string
		lineageTag: cb5fe527-7e6c-430a-8bcb-5215bb87e397
		summarizeBy: none
		sourceColumn: Column9

		annotation SummarizationSetBy = Automatic

	column Column10
		dataType: string
		lineageTag: afdd1595-c0e6-4601-9336-ed8fa5ce6c64
		summarizeBy: none
		sourceColumn: Column10

		annotation SummarizationSetBy = Automatic

	column Column11
		dataType: string
		lineageTag: 0efb8d49-ad93-4019-a7a6-0ed8bbc92d84
		summarizeBy: none
		sourceColumn: Column11

		annotation SummarizationSetBy = Automatic

	column Column12
		dataType: string
		lineageTag: e09490f0-5bee-4557-809b-5f3d3675634a
		summarizeBy: none
		sourceColumn: Column12

		annotation SummarizationSetBy = Automatic

	column Column13
		dataType: string
		lineageTag: b2ec02d4-5421-49f3-9d8a-74e57491a5e5
		summarizeBy: none
		sourceColumn: Column13

		annotation SummarizationSetBy = Automatic

	column Column14
		dataType: string
		lineageTag: 53ac34aa-cc03-4f2b-8fe6-2814e23096d0
		summarizeBy: none
		sourceColumn: Column14

		annotation SummarizationSetBy = Automatic

	column Column15
		dataType: string
		lineageTag: 059f568a-304e-4182-9302-7dba9c4fe32b
		summarizeBy: none
		sourceColumn: Column15

		annotation SummarizationSetBy = Automatic

	column Column16
		dataType: string
		lineageTag: f840fa16-47b7-4a34-ae88-b4416a651256
		summarizeBy: none
		sourceColumn: Column16

		annotation SummarizationSetBy = Automatic

	column Column17
		dataType: string
		lineageTag: d49ca09d-19f7-4265-8f90-11bac04d65e9
		summarizeBy: none
		sourceColumn: Column17

		annotation SummarizationSetBy = Automatic

	column Column18
		dataType: string
		lineageTag: 3935d4b7-a268-469a-85ee-92aa61e48e93
		summarizeBy: none
		sourceColumn: Column18

		annotation SummarizationSetBy = Automatic

	column Column19
		dataType: string
		lineageTag: d52d494d-8f5f-4afc-bf74-dd61ce5a96fc
		summarizeBy: none
		sourceColumn: Column19

		annotation SummarizationSetBy = Automatic

	column Column20
		dataType: string
		lineageTag: 40bc99c0-90f9-4ab3-b62e-9c211f782dba
		summarizeBy: none
		sourceColumn: Column20

		annotation SummarizationSetBy = Automatic

	column Column21
		dataType: string
		lineageTag: bd549762-9e16-4422-be04-373c7d3cbd1f
		summarizeBy: none
		sourceColumn: Column21

		annotation SummarizationSetBy = Automatic

	column Column22
		dataType: string
		lineageTag: d3b53291-20e7-4e93-bc97-685196670c98
		summarizeBy: none
		sourceColumn: Column22

		annotation SummarizationSetBy = Automatic

	column Column23
		dataType: string
		lineageTag: 02a2feb1-2d80-412c-a301-1124cd385386
		summarizeBy: none
		sourceColumn: Column23

		annotation SummarizationSetBy = Automatic

	column Column24
		dataType: string
		lineageTag: f3488b91-b791-4a79-8364-ae91cb78d2f3
		summarizeBy: none
		sourceColumn: Column24

		annotation SummarizationSetBy = Automatic

	column Column25
		dataType: string
		lineageTag: 17346fcd-d5f6-49c8-88bc-32de364d34f8
		summarizeBy: none
		sourceColumn: Column25

		annotation SummarizationSetBy = Automatic

	column Column26
		dataType: string
		lineageTag: 05d156a2-1dd4-4b7c-aa22-de42dacbc3ab
		summarizeBy: none
		sourceColumn: Column26

		annotation SummarizationSetBy = Automatic

	column Column27
		dataType: string
		lineageTag: 6e2a41d5-0f77-4da1-9dda-37873f1e65ba
		summarizeBy: none
		sourceColumn: Column27

		annotation SummarizationSetBy = Automatic

	partition Dates = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\Kanisk Jaiswal\Downloads\QUESTION_Connection2POWERBI.xlsx"), null, true),
				    Dates_Sheet = Source{[Item="Dates",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(Dates_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Date", Int64.Type}, {"Day Name", type text}, {"Day", Int64.Type}, {"Week", Int64.Type}, {"Month", Int64.Type}, {"Quarter", Int64.Type}, {"Year", Int64.Type}, {"Column8", type any}, {"Column9", type any}, {"Column10", type any}, {"Column11", type any}, {"Column12", type any}, {"Column13", type any}, {"Column14", type any}, {"Column15", type any}, {"Column16", type any}, {"Column17", type any}, {"Column18", type any}, {"Column19", type any}, {"Column20", type any}, {"Column21", type any}, {"Column22", type any}, {"Column23", type any}, {"Column24", type any}, {"Column25", type any}, {"Column26", type any}, {"Column27", type any}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

