table Products
	lineageTag: 1d73670e-d1d2-40b1-b0b5-fc7a798f4dce

	column 'Product ID'
		dataType: string
		lineageTag: a5444e8b-e7b0-4234-9ea8-fd044f22b620
		summarizeBy: none
		sourceColumn: Product ID

		annotation SummarizationSetBy = Automatic

	column Category
		dataType: string
		lineageTag: 7bbf5889-149a-487e-8f08-6ca924125cc2
		summarizeBy: none
		sourceColumn: Category

		annotation SummarizationSetBy = Automatic

	column Sub-Category
		dataType: string
		lineageTag: 20cce885-08d0-4b86-9f3d-ee7f720023e7
		summarizeBy: none
		sourceColumn: Sub-Category

		annotation SummarizationSetBy = Automatic

	column 'Product Name'
		dataType: string
		lineageTag: 63ee0b9f-9fea-48c1-8187-2b70556d351a
		summarizeBy: none
		sourceColumn: Product Name

		annotation SummarizationSetBy = Automatic

	column 'List price'
		dataType: int64
		formatString: 0
		lineageTag: f866d736-7a4d-4711-89d8-c45daeecf693
		summarizeBy: sum
		sourceColumn: List price

		annotation SummarizationSetBy = Automatic

	column Column6
		dataType: string
		lineageTag: 7d323960-7c50-4cc1-8121-e705f93593a2
		summarizeBy: none
		sourceColumn: Column6

		annotation SummarizationSetBy = Automatic

	column Column7
		dataType: string
		lineageTag: 119459eb-157c-4153-a88a-96057134cdbe
		summarizeBy: none
		sourceColumn: Column7

		annotation SummarizationSetBy = Automatic

	column Column8
		dataType: string
		lineageTag: 2fd4c51e-5ecc-401a-ab53-371ede4230ed
		summarizeBy: none
		sourceColumn: Column8

		annotation SummarizationSetBy = Automatic

	column Column9
		dataType: string
		lineageTag: 50194ee0-0ca6-4789-a2f4-722d471b05e5
		summarizeBy: none
		sourceColumn: Column9

		annotation SummarizationSetBy = Automatic

	column Column10
		dataType: string
		lineageTag: 77f48d16-1a46-44f7-99f6-83b744db506d
		summarizeBy: none
		sourceColumn: Column10

		annotation SummarizationSetBy = Automatic

	column Column11
		dataType: string
		lineageTag: 4e506f80-220a-4bc9-b644-5644bc227267
		summarizeBy: none
		sourceColumn: Column11

		annotation SummarizationSetBy = Automatic

	column Column12
		dataType: string
		lineageTag: 0fa63a14-e9f8-4f02-a102-45391d47b1bb
		summarizeBy: none
		sourceColumn: Column12

		annotation SummarizationSetBy = Automatic

	column Column13
		dataType: string
		lineageTag: 02763c2e-d317-42ac-b3aa-1e9bb9ff0fd5
		summarizeBy: none
		sourceColumn: Column13

		annotation SummarizationSetBy = Automatic

	column Column14
		dataType: string
		lineageTag: c8ea71bd-f98a-4a34-9128-8f3d3b0e7ffd
		summarizeBy: none
		sourceColumn: Column14

		annotation SummarizationSetBy = Automatic

	column Column15
		dataType: string
		lineageTag: 330301a3-fccc-47d1-8ad2-954ff0ded0a1
		summarizeBy: none
		sourceColumn: Column15

		annotation SummarizationSetBy = Automatic

	column Column16
		dataType: string
		lineageTag: 21f78f66-37fa-4c69-bc3e-aa682ed17cfe
		summarizeBy: none
		sourceColumn: Column16

		annotation SummarizationSetBy = Automatic

	column Column17
		dataType: string
		lineageTag: 0c6c60f3-8151-4876-bc55-97c351835c78
		summarizeBy: none
		sourceColumn: Column17

		annotation SummarizationSetBy = Automatic

	column Column18
		dataType: string
		lineageTag: 2a7129c2-d1fa-42b4-b215-45a1dbfb18f0
		summarizeBy: none
		sourceColumn: Column18

		annotation SummarizationSetBy = Automatic

	column Column19
		dataType: string
		lineageTag: 11711ed1-143e-4d43-a068-9b8ab74f7c2b
		summarizeBy: none
		sourceColumn: Column19

		annotation SummarizationSetBy = Automatic

	column Column20
		dataType: string
		lineageTag: e5eaf761-158f-4ddc-869f-a57a20ce10db
		summarizeBy: none
		sourceColumn: Column20

		annotation SummarizationSetBy = Automatic

	column Column21
		dataType: string
		lineageTag: bcba68c7-516a-484f-acdc-16827e440a97
		summarizeBy: none
		sourceColumn: Column21

		annotation SummarizationSetBy = Automatic

	column Column22
		dataType: string
		lineageTag: dd01902a-8cb3-4268-be07-7b877b02b986
		summarizeBy: none
		sourceColumn: Column22

		annotation SummarizationSetBy = Automatic

	partition Products = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\Kanisk Jaiswal\Downloads\QUESTION_Connection2POWERBI.xlsx"), null, true),
				    Products_Sheet = Source{[Item="Products",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(Products_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Product ID", type text}, {"Category", type text}, {"Sub-Category", type text}, {"Product Name", type text}, {"List price", Int64.Type}, {"Column6", type any}, {"Column7", type any}, {"Column8", type any}, {"Column9", type any}, {"Column10", type any}, {"Column11", type any}, {"Column12", type any}, {"Column13", type any}, {"Column14", type any}, {"Column15", type any}, {"Column16", type any}, {"Column17", type any}, {"Column18", type any}, {"Column19", type any}, {"Column20", type any}, {"Column21", type any}, {"Column22", type any}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

